# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_list.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 564)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reload_btn = QtWidgets.QPushButton(Form)
        self.reload_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.reload_btn.setFont(font)
        self.reload_btn.setObjectName("reload_btn")
        self.horizontalLayout_2.addWidget(self.reload_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.reverse = QtWidgets.QCheckBox(Form)
        self.reverse.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.reverse.setFont(font)
        self.reverse.setObjectName("reverse")
        self.horizontalLayout_2.addWidget(self.reverse)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.low_id = QtWidgets.QSpinBox(Form)
        self.low_id.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.low_id.setFont(font)
        self.low_id.setSingleStep(0)
        self.low_id.setObjectName("low_id")
        self.horizontalLayout_2.addWidget(self.low_id)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.high_id = QtWidgets.QSpinBox(Form)
        self.high_id.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.high_id.setFont(font)
        self.high_id.setMaximum(100)
        self.high_id.setProperty("value", 100)
        self.high_id.setObjectName("high_id")
        self.horizontalLayout_2.addWidget(self.high_id)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.no_btn = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.no_btn.setFont(font)
        self.no_btn.setChecked(True)
        self.no_btn.setObjectName("no_btn")
        self.horizontalLayout.addWidget(self.no_btn)
        self.a_btn = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.a_btn.setFont(font)
        self.a_btn.setObjectName("a_btn")
        self.horizontalLayout.addWidget(self.a_btn)
        self.b_btn = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.b_btn.setFont(font)
        self.b_btn.setObjectName("b_btn")
        self.horizontalLayout.addWidget(self.b_btn)
        self.c_btn = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_btn.setFont(font)
        self.c_btn.setObjectName("c_btn")
        self.horizontalLayout.addWidget(self.c_btn)
        self.d_btn = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.d_btn.setFont(font)
        self.d_btn.setObjectName("d_btn")
        self.horizontalLayout.addWidget(self.d_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)

        self.retranslateUi(Form)
        self.reload_btn.clicked.connect(Form.reload)
        self.reverse.toggled['bool'].connect(Form.reload)
        self.no_btn.clicked.connect(Form.reload)
        self.a_btn.clicked.connect(Form.reload)
        self.b_btn.clicked.connect(Form.reload)
        self.c_btn.clicked.connect(Form.reload)
        self.d_btn.clicked.connect(Form.reload)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.reload_btn.setText(_translate("Form", "刷新"))
        self.reverse.setText(_translate("Form", "倒序"))
        self.label.setText(_translate("Form", "序号区间："))
        self.label_2.setText(_translate("Form", "<->"))
        self.label_3.setText(_translate("Form", "卡片等级"))
        self.no_btn.setText(_translate("Form", "不筛选"))
        self.a_btn.setText(_translate("Form", "A"))
        self.b_btn.setText(_translate("Form", "B"))
        self.c_btn.setText(_translate("Form", "C"))
        self.d_btn.setText(_translate("Form", "D"))
